server:
  port: 8980

spring:
  application:
    name: zuul-server
  mail:
    host: "smtphm.qiye.163.com" #SMTP服务器地址
    username: "sunzhemin@yunzhangfang.com" #登陆账号
    password: "" #登陆密码（或授权码）
    properties:
      from:  "sunzhemin@yunzhangfang.com" #邮件发信人（即真实邮箱）
  thymeleaf:
    cache: false
    prefix: classpath:/views/
  servlet:
    multipart:
      max-file-size: 10MB #限制单个文件大小
      max-request-size: 50MB #限制请求总量

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always

